kind: source
spec:
  name: mysql
  path: cloudquery/mysql
  version: v5.0.5
  write_mode: overwrite-delete-stale
  migrate_mode: safe
  spec:
    connection_string: sql5700808:Gjw3Kc8QK2@tcp(sql5.freemysqlhosting.net:3306)/sql5700808
